In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame

In [17]:
df = pd.read_csv('Test3_Full_Original.csv',
            delimiter=',', names=['x', 'y', 'Magicv2', 'localization4', 'localizationlab', 'Magicv2_5g', 'UVIC_Eduroam1', 'UVIC_Eduroam2', 'localization3', 'localization_lab5g', 'localization1', 'localization4_5g', 'UVIC_Eduroam3', 'localization2', 'localization3_5g', 'UVIC_Eduroam4', 'localization1_5g'])
df = df.loc[:,['Magicv2', 'localization4', 'localizationlab', 'Magicv2_5g', 
       'localization3', 'localization_lab5g', 'localization1', 'localization4_5g', 'localization2',
       'localization3_5g', 'localization1_5g']]

In [36]:
#Get 11 Zscores for the 11 fingerprints
df['zscore1'] = (df.Magicv2 - df.Magicv2.mean())/(df.Magicv2.std())
df['zscore2'] = (df.localization4 - df.localization4.mean())/(df.localization4.std())
df['zscore3'] = (df.localizationlab - df.localizationlab.mean())/(df.localizationlab.std())
df['zscore4'] = (df.Magicv2_5g - df.Magicv2_5g.mean())/(df.Magicv2_5g.std())
df['zscore5'] = (df.localization3 - df.localization3.mean())/(df.localization3.std())
df['zscore6'] = (df.localization_lab5g - df.localization_lab5g.mean())/(df.localization_lab5g.std())
df['zscore7'] = (df.localization1 - df.localization1.mean())/(df.localization1.std())
df['zscore8'] = (df.localization4_5g - df.localization4_5g.mean())/(df.localization4_5g.std())
df['zscore9'] = (df.localization2 - df.localization2.mean())/(df.localization2.std())
df['zscore10'] = (df.localization3_5g - df.localization3_5g.mean())/(df.localization3_5g.std())
df['zscore11'] = (df.localization1_5g - df.localization1_5g.mean())/(df.localization1_5g.std())

In [37]:
df[(df['zscore1'] > 3)| (df['zscore1'] < -3)] #magicv2

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
501,-80,-60,-79,-90,-53,-92,-74,-97,-61,-60,...,-0.594498,-1.4841,-0.580332,-1.950253,-1.049224,0.003654,-1.346921,0.704769,-0.398421,1.150145

In [38]:
df[(df['zscore2'] > 3)| (df['zscore2'] < -3)] #localization4

Empty DataFrame
Columns: [Magicv2, localization4, localizationlab, Magicv2_5g, localization3, localization_lab5g, localization1, localization4_5g, localization2, localization3_5g, localization1_5g, zscore, zscore1, zscore2, zscore3, zscore4, zscore5, zscore6, zscore7, zscore8, zscore9, zscore10, zscore11]
Index: []

[0 rows x 23 columns]

In [39]:
df[(df['zscore3'] > 3)| (df['zscore3'] < -3)] #localizationlab

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
373,-61,-61,-100,-91,-38,-88,-75,-95,-64,-56,...,-0.755104,-4.509462,-0.735487,-0.035616,-0.287046,-0.109624,-1.067860,0.294353,0.306347,-0.001858
459,-68,-60,-100,-92,-47,-93,-70,-95,-58,-57,...,-0.594498,-4.509462,-0.890643,-1.184398,-1.239768,0.456765,-1.067860,1.115186,0.130155,0.327286
488,-71,-64,-100,-92,-51,-93,-70,-98,-56,-61,...,-1.236919,-4.509462,-0.890643,-1.694968,-1.239768,0.456765,-1.486452,1.388797,-0.574613,0.162714
489,-71,-61,-100,-91,-51,-93,-70,-95,-56,-61,...,-0.755104,-4.509462,-0.735487,-1.694968,-1.239768,0.456765,-1.067860,1.388797,-0.574613,-0.001858
490,-71,-58,-100,-91,-51,-93,-70,-94,-56,-61,...,-0.273288,-4.509462,-0.735487,-1.694968,-1.239768,0.456765,-0.928329,1.388797,-0.574613,-0.001858
491,-69,-60,-100,-92,-51,-93,-70,-94,-54,-61,...,-0.594498,-4.509462,-0.890643,-1.694968,-1.239768,0.456765,-0.928329,1.662408,-0.574613,-0.001858
492,-71,-60,-100,-92,-51,-93,-70,-95,-56,-61,...,-0.594498,-4.509462,-0.890643,-1.694968,-1.239768,0.456765,-1.067860,1.388797,-0.574613,-0.001858
493,-73,-60,-100,-92,-51,-93,-70,-95,-56,-61,...,-0.594498,-4.509462,-0.890643,-1.694968,-1.239768,0.456765,-1.067860,1.388797,-0.574613,-0.001858
494,-72,-58,-100,-92,-50,-93,-70,-95,-56,-61,...,-0.273288,-4.509462,-0.890643,-1.567326,-1.239768,0.456765,-1.067860,1.388797,-0.574613,-0.001858
520,-74,-67,-100,-93,-47,-93,-69,-93,-58,-66,...,-1.718735,-4.509462,-1.045798,-1.184398,-1.239768,0.570043,-0.788798,1.115186,-1.455574,0.985573
560,-71,-60,-100,-94,-46,-89,-65,-95,-55,-66,...,-0.594498,-4.509462,-1.200954,-1.056756,-0.477590,1.023154,-1.067860,1.525602,-1.455574,1.643860
561,-71,-60,-100,-91,-46,-89,-60,-95,-55,-66,...,-0.594498,-4.509462,-0.735487,-1.056756,-0.477590,1.589542,-1.067860,1.525602,-1.455574,1.643860
562,-71,-59,-100,-91,-46,-89,-63,-95,-55,-68,...,-0.433893,-4.509462,-0.735487,-1.056756,-0.477590,1.249709,-1.067860,1.525602,-1.807958,1.643860
581,-74,-62,-100,-93,-44,-87,-63,-94,-58,-67,...,-0.915709,-4.509462,-1.045798,-0.801471,-0.096502,1.249709,-0.928329,1.115186,-1.631766,2.466719
582,-71,-62,-100,-93,-44,-87,-63,-94,-59,-65,...,-0.915709,-4.509462,-1.045798,-0.801471,-0.096502,1.249709,-0.928329,0.978380,-1.279382,2.466719
583,-71,-62,-100,-94,-44,-87,-63,-94,-59,-66,...,-0.915709,-4.509462,-1.200954,-0.801471,-0.096502,1.249709,-0.928329,0.978380,-1.455574,2.466719
584,-71,-63,-100,-94,-44,-88,-63,-94,-59,-66,...,-1.076314,-4.509462,-1.200954,-0.801471,-0.287046,1.249709,-0.928329,0.978380,-1.455574,2.302147
585,-71,-63,-100,-94,-44,-87,-63,-94,-59,-66,...,-1.076314,-4.509462,-1.200954,-0.801471,-0.096502,1.249709,-0.928329,0.978380,-1.455574,2.302147
601,-70,-63,-100,-93,-48,-85,-60,-91,-56,-66,...,-1.076314,-4.509462,-1.045798,-1.312041,0.284587,1.589542,-0.509737,1.388797,-1.455574,2.795863

In [40]:
df[(df['zscore4'] > 3)| (df['zscore4'] < -3)] #magicv2

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
0,-56,-45,-66,-66,-41,-79,-76,-73,-75,-61,...,1.814580,0.388743,3.143401,-0.418544,1.427854,-0.222901,2.001815,-1.210508,-0.574613,0.327286
1,-56,-45,-63,-65,-41,-78,-73,-68,-75,-63,...,1.814580,0.820937,3.298557,-0.418544,1.618398,0.116932,2.699469,-1.210508,-0.926998,-0.495574
9,-56,-45,-66,-65,-38,-79,-73,-67,-70,-56,...,1.814580,0.388743,3.298557,-0.035616,1.427854,0.116932,2.838999,-0.526481,0.306347,-0.331002
13,-53,-42,-64,-65,-35,-74,-76,-68,-75,-56,...,2.296395,0.676872,3.298557,0.347311,2.380576,-0.222901,2.699469,-1.210508,0.306347,-0.166430
14,-53,-43,-64,-65,-35,-74,-76,-68,-75,-56,...,2.135790,0.676872,3.298557,0.347311,2.380576,-0.222901,2.699469,-1.210508,0.306347,-0.166430
15,-53,-43,-65,-64,-35,-74,-76,-67,-72,-56,...,2.135790,0.532808,3.453713,0.347311,2.380576,-0.222901,2.838999,-0.800092,0.306347,-0.166430
16,-55,-40,-66,-64,-35,-74,-76,-67,-72,-56,...,2.617606,0.388743,3.453713,0.347311,2.380576,-0.222901,2.838999,-0.800092,0.306347,-0.001858
17,-55,-41,-63,-63,-34,-74,-77,-68,-72,-56,...,2.457001,0.820937,3.608868,0.474953,2.380576,-0.336179,2.699469,-0.800092,0.306347,-0.001858
18,-55,-41,-63,-63,-34,-74,-77,-66,-73,-56,...,2.457001,0.820937,3.608868,0.474953,2.380576,-0.336179,2.978530,-0.936897,0.306347,0.162714
19,-54,-39,-63,-64,-34,-76,-77,-65,-74,-56,...,2.778211,0.820937,3.453713,0.474953,1.999487,-0.336179,3.118061,-1.073703,0.306347,-0.495574

In [41]:
df[(df['zscore5'] > 3)| (df['zscore5'] < -3)] #localization3

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
600,-72,-63,-71,-93,-65,-84,-63,-92,-59,-66,...,-1.076314,-0.331582,-1.045798,-3.481962,0.475132,1.249709,-0.649268,0.97838,-1.455574,2.466719

In [42]:
df[(df['zscore6'] > 3)| (df['zscore6'] < -3)] #localization_lab5g

Empty DataFrame
Columns: [Magicv2, localization4, localizationlab, Magicv2_5g, localization3, localization_lab5g, localization1, localization4_5g, localization2, localization3_5g, localization1_5g, zscore, zscore1, zscore2, zscore3, zscore4, zscore5, zscore6, zscore7, zscore8, zscore9, zscore10, zscore11]
Index: []

[0 rows x 23 columns]

In [43]:
df[(df['zscore7'] > 3)| (df['zscore7'] < -3)] #localization1

Empty DataFrame
Columns: [Magicv2, localization4, localizationlab, Magicv2_5g, localization3, localization_lab5g, localization1, localization4_5g, localization2, localization3_5g, localization1_5g, zscore, zscore1, zscore2, zscore3, zscore4, zscore5, zscore6, zscore7, zscore8, zscore9, zscore10, zscore11]
Index: []

[0 rows x 23 columns]

In [44]:
df[(df['zscore8'] > 3)| (df['zscore8'] < -3)] #localization4_lab5g

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
19,-54,-39,-63,-64,-34,-76,-77,-65,-74,-56,...,2.778211,0.820937,3.453713,0.474953,1.999487,-0.336179,3.118061,-1.073703,0.306347,-0.495574

In [45]:
df[(df['zscore9'] > 3)| (df['zscore9'] < -3)] #localization2

,Magicv2,localization4,localizationlab,Magicv2_5g,localization3,localization_lab5g,localization1,localization4_5g,localization2,localization3_5g,...,zscore2,zscore3,zscore4,zscore5,zscore6,zscore7,zscore8,zscore9,zscore10,zscore11
81,-59,-52,-73,-86,-34,-87,-100,-87,-100,-54,...,0.690343,-0.619711,0.040290,0.474953,-0.096502,-2.941567,0.048386,-4.630646,0.658731,-0.660145
82,-59,-50,-69,-86,-34,-86,-77,-85,-100,-54,...,1.011554,-0.043452,0.040290,0.474953,0.094043,-0.336179,0.327447,-4.630646,0.658731,-0.660145
83,-59,-51,-69,-86,-34,-86,-77,-86,-100,-54,...,0.850949,-0.043452,0.040290,0.474953,0.094043,-0.336179,0.187916,-4.630646,0.658731,-0.495574
281,-63,-49,-64,-84,-42,-79,-69,-84,-100,-54,...,1.172159,0.676872,0.350602,-0.546186,1.427854,0.570043,0.466978,-4.630646,0.658731,-0.495574

In [46]:
df[(df['zscore10'] > 3)| (df['zscore10'] < -3)] #localization2

Empty DataFrame
Columns: [Magicv2, localization4, localizationlab, Magicv2_5g, localization3, localization_lab5g, localization1, localization4_5g, localization2, localization3_5g, localization1_5g, zscore, zscore1, zscore2, zscore3, zscore4, zscore5, zscore6, zscore7, zscore8, zscore9, zscore10, zscore11]
Index: []

[0 rows x 23 columns]

In [47]:
df[(df['zscore11'] > 3)| (df['zscore11'] < -3)] #localization3_5g

Empty DataFrame
Columns: [Magicv2, localization4, localizationlab, Magicv2_5g, localization3, localization_lab5g, localization1, localization4_5g, localization2, localization3_5g, localization1_5g, zscore, zscore1, zscore2, zscore3, zscore4, zscore5, zscore6, zscore7, zscore8, zscore9, zscore10, zscore11]
Index: []

[0 rows x 23 columns]

In [1]:
#for i in df['Magicv2'].iteritems():
 #   if(df['zscore1'].iloc[i, 12] > 3):
  #      print('hello')